# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:SLS_ORG}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: notion-fitnotes
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notion-fitnotes

provider:
  name: aws
  runtime: python3.13
  environment:
    NOTION_API_KEY: ${env:NOTION_API_KEY}
    NOTION_BODYWEIGHT_DATABASE_ID: ${env:NOTION_BODYWEIGHT_DATABASE_ID}
    NOTION_EXERCISE_DATABASE_ID: ${env:NOTION_EXERCISE_DATABASE_ID}
functions:
  sync:
    handler: db_sync.run
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - schedule: rate(1 hour)

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-python-requirements
package:
  exclude:
    - .venv/**

custom:
  pythonRequirements:
    slim: true
    zip: true
    layer: true
